Output ../public/togglemesh-cli.gif

Set FontSize 22
Set FontFamily "Cascadia Code"
Set Width 1280
Set Height 720
Set WindowBar Colorful
Set Margin 20
Set Padding 30

Hide
Type "cls"
Enter
Show

Sleep 0.5s
Type "togglemesh config"
Enter
Sleep 1s
Type "y"
Sleep 0.5s
Enter
Sleep 1s
Copy "tmp_******************************************"
Paste
Sleep 0.5s
Enter
Sleep 1s
Copy "********-****-****-****-************"
Paste
Sleep 0.5s
Enter
Sleep 1s
Type "app.togglemesh.dev"
Sleep 0.5s
Enter
Sleep 1.5s
Enter
Sleep 1.5s
Enter
Sleep 3s

Type "cls"
Sleep 0.2s
Enter
Sleep 1s

Type "togglemesh sync"
Enter
Sleep 4s
Type "y"
Sleep 0.5s
Enter
Sleep 2s
